# SPDX-FileCopyrightText: 2020 Nicolas Fella <nicolas.fella@gmx.de>
# SPDX-FileCopyrightText: 2020 Tobias Fella <fella@posteo.de>
# SPDX-License-Identifier: BSD-2-Clause

include:
  - https://invent.kde.org/sysadmin/ci-tooling/raw/master/invent/ci-before.yml
  - https://invent.kde.org/sysadmin/ci-tooling/raw/master/invent/ci-extragear-linux.yml
  - https://invent.kde.org/sysadmin/ci-tooling/raw/master/invent/ci-reuse.yml

android:
  variables:
    CI_TOOLING: /home/user/ci-tooling

  stage: build
  image: kdeorg/android-sdk

  artifacts:
    paths:
      - "*.apk"

  script:
    - cd /home/user
    - /opt/helpers/build-kde-dependencies $CI_PROJECT_NAME
    - APK_ARGS=`python3 /opt/helpers/get-apk-args.py $CI_PROJECT_DIR`
    - /opt/helpers/build-cmake $CI_PROJECT_NAME $CI_PROJECT_DIR $APK_ARGS -DANDROID_APK_OUTPUT_DIR=$CI_PROJECT_DIR
    - pushd build-arm/$CI_PROJECT_NAME
    - make create-apk
    - popd
    - pushd build-arm64/$CI_PROJECT_NAME
    - make create-apk
    - popd
